{% set name = "dials-dependencies" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7feabcdd4c2701b819f030bbc03806fc08a4b9820e4e1f41c0559380f39e2cf

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2
    - mock >=3.0.5
    - msgpack-c
    - msgpack-python
    - orderedset
    - procrunner >=1.0.2
    - pytest >=4.5,<5.0
    - pytest-mock
    - pytest-xdist >=1.28.0
    - scikit-learn <0.21
    - scipy
    - six
    - tqdm =4.23.4

test:
  imports:
    - dials_dependencies
  requires:
    - pytest
  commands:
    - py.test --pyargs dials_dependencies

about:
  home: https://dials.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Conda-package describing DIALS dependencies'

  description: |
    DIALS <https://dials.github.io> is the Diffraction Integration for
    Advanced Light Sources package, used to integrate crystallographic data.
    It has a large set of complex dependencies and currently can not be easily
    installed via pip or conda. This package aims to make the installation
    process less cumbersome.
  dev_url: https://github.com/dials/dials-dependencies

extra:
  recipe-maintainers:
    - anthchirp
