{% set name = "dials-dependencies" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cabd0e136a2d888f96eeb006887fb67546dc15284d5e3933ab442319dc9d0b2e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dials_dependencies
  requires:
    - pytest
  commands:
    - py.test --pyargs dials_dependencies

about:
  home: https://dials.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Conda-package describing DIALS dependencies'

  description: |
    DIALS <https://dials.github.io> is the Diffraction Integration for
    Advanced Light Sources package, used to integrate crystallographic data.
    It has a large set of complex dependencies and currently can not be easily
    installed via pip or conda. This package aims to make the installation
    process less cumbersome.
  dev_url: https://github.com/dials/dials-dependencies

extra:
  recipe-maintainers:
    - anthchirp
