travis:
  secure:
    BINSTAR_TOKEN: xESfPj97yFz2r+Qig4DZSnQmnpARPejKOh7z9GS6f+OJus/4RJFaRZTvaO+n2y1woza9qP3v9LL81C7a4bRbOLYDYO2Om1fmy2u/BJia43rFD/l0KHv3D+T/kJV7xzqVE7r8TIz/z11H3edVB7I9m7wgq+BIMSBsKtYeZOGpcQBEFZX8DZSRACNHu8Izp/XnnPRWIZWVsjG0SpVrsmLIZ/LlLFRLN0EVHkmyF0UXGJlr1kY0AEgT4/9kSBn1BTZNXQRj3wTqw3M0XTnquYgwaCVKH6O/TRYiiiUicAHett343iJZskcoAIqOj+W+k3dRnRMNW10QFOYY+A1BVwx3GeMlRPAxjCLlTXI5mgixutuRJ9vTN7hu8i+S5OOYP0Uv5yLMvEzj0XllOEJdN1SJ9LDv2KUjUHauwFdga0E4gONUj6W+G0jzE9RttNEvhDOpiBuetOJ0lIrboCpGjQUh28AvdPfPvFylRUlU1wxydTRCw6SKrp9wbmFdNKWEYg89WQOfgAR1Fs8IXGvAj5qVTQGbuTp6K9wObfoDNuzoMvzLlEZLnWdaw4h9cjrbl0gqGzDVCsQmDqVubLxyBir+N2T0VobnzNCnIbsv3SRd5iFi+bkHGxLpxGqBB6O0vCPBSWHi4MNiFFPhb/VYz+JodEY27WoLVAqkrEmje4d+0yw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
